### ISSUE TITLE
Responsive menu

### ISSUE THREAD

**Issue by QMarbois** [cefim/dwwm2021-1-superapp#1]
There is a problem with your menu. 
Everything works fine until the width breakpoint at 576px.
After this breakpoint, your menu takes a bad position in your navigation except if you let it open before going over 576px and then keep hidden attribute setted to false
Without this little hacking, your menu still has hidden attribute setted to true after 576px.
![bug_menu_superapp](https://user-images.githubusercontent.com/81381419/114283366-ac5d0700-9a49-11eb-88a0-2fd27e9e1f04.png)

**Comment by blawniczak** [comment]
Fixed. Thank you :)
